### ISSUE TITLE
[Feature] 2차 테스트 피드백 수정

### ISSUE THREAD

**Issue by dmeiei** [APP-Android2/FinalProject-modigm#374]
## 어떤 기능인가요?

> 테스트 하면서 발견된 버그 수정

## 작업 상세 내용

- [x] 프로필 이미지 초기화 문제
- [x] 소개글 작성 edittext에 스크롤 추가
- [x] 알림페이지에 알림이 없는 경우 나오는 화면이 안보이는 문제
- [x] 참여중인 멤버 정렬 수정
- [x] 알림 배지 사라지는 문제
- [x] 스터디 정원이 다 찼을 경우 신청 막기
- [x] 신청하기 버튼 클릭시 스낵바 여러개 보이는 문제
- [x] 설정 부분 알림 파트 삭제
- [ ] 등등

**Comment by language7606** [comment]
설정부분 알림 제거 제가 하는 줄 알고, 하고서 PR 올렸네요;; ㅎㅎ 그 부분만 제가 적용하는 걸로 하겠습니다!
@dmeiei
